services:
  mysql:
    image: mysql:8.0
    container_name: sakila_mysql
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/sakila-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/sakila-data.sql:/docker-entrypoint-initdb.d/2-data.sql

    healthcheck:
      test: ['CMD-SHELL', "mysql -u root -p${DB_ROOT_PASSWORD} -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  app:
    image: maven:3.9-eclipse-temurin-17
    container_name: sakila_app_dev
    working_dir: /app

    volumes:
      - .:/app
      - maven_cache:/root/.m2

    env_file:
      - .env

    command: >
      sh -c "
      apt-get update && apt-get install -y netcat-openbsd mysql-client &&
      echo START WAIT LOOP &&

      until nc -z mysql 3306; do
        echo WAITING TCP mysql:3306;
        sleep 2;
      done;
      echo TCP OK;

      until mysql -h mysql -u${DB_USER} -p${DB_PASSWORD} ${DB_NAME} -e 'SELECT 1' > /dev/null 2>&1; do
        echo WAITING MYSQL READY;
        sleep 3;
      done;
      echo MYSQL READY;

      echo STARTING SPRING;
      mvn spring-boot:run
      "

    ports:
      - '8080:8080'

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  maven_cache:
